# Use the official Node.js image as the base image
FROM node:18-alpine AS base

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm i

# Copy the rest of the application code to the container
COPY . .

# Pass FIREBASE_CONFIG as a build argument
ARG FIREBASE_CONFIG
ENV FIREBASE_CONFIG=$FIREBASE_CONFIG

# Build the Next.js application
RUN npm run build

# Expose the port the Next.js app will run on
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "start"]