name: Deploy Terraform Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_TERRAFORM_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "region=${{ vars.GCP_REGION }}"

    - name: Verify API
      run: |
        gcloud run services describe api --region=${{ vars.GCP_REGION }} --project=${{ secrets.GCP_PROJECT_ID }}

    - name: Verify Frontend
      run: |
        gcloud run services describe frontend --region=${{ vars.GCP_REGION }} --project=${{ secrets.GCP_PROJECT_ID }}