name: Deploy Frontend to Cloud Run

on:
  workflow_run:
    workflows: ["Deploy Terraform Infrastructure"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Update HTML file
      working-directory: frontend
      run: |
        node replace_url.js ${{ secrets.GCP_API }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_TERRAFORM_SA_KEY }}
  
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
  
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

    - name: Build Docker image
      working-directory: frontend
      run: |
        docker build -t ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jwdev/frontend:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jwdev/frontend:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy frontend \
          --image ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jwdev/frontend:latest \
          --region ${{ vars.GCP_REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 