name: Deploy Daily Devops API to Cloud Run

on:
  workflow_run:
    workflows: ["Deploy Terraform Infrastructure"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_TERRAFORM_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

    - name: Build Docker image
      working-directory: backend/api
      run: |
        docker build -t ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jwdev/api:latest .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jwdev/api:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy api \
          --image ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/jwdev/api:latest \
          --platform managed \
          --region ${{ vars.GCP_REGION }} \
          --port 8080 \
          --allow-unauthenticated \
          --service-account ${{ secrets.GCP_TF_SA_ADDRESS }}